FROM denoland/deno:1.30.2

WORKDIR /app

USER deno

COPY src/shared/deps/ shared/deps/
COPY deno.json deno.lock ./
RUN deno cache shared/deps/all.ts

ADD src/shared/ shared/
ADD src/worker/ worker/
RUN deno cache worker/main.ts

CMD [ "deno", "run", "--allow-net", "--allow-env", "--allow-run", "--allow-read", "worker/main.ts" ]
