FROM denoland/deno:1.24.0

WORKDIR /app

USER deno

COPY src/shared/deps/ shared/deps/
RUN deno cache shared/deps/all.ts

ADD src/shared/ shared/
ADD src/worker/ worker/
RUN deno cache worker/main.ts

CMD [ "deno", "run", "--allow-net", "--allow-env", "--allow-run", "--allow-read", "worker/main.ts" ]
