FROM denoland/deno:1.30.2

WORKDIR /app

USER deno

COPY /src/shared/deps/ shared/deps/
COPY deno.json deno.lock ./
RUN deno cache shared/deps/all.ts

ADD /migrations/ migrations/
ADD /src/shared/ shared/
ADD /src/migrator/ migrator
RUN deno cache migrator/main.ts

CMD [ "deno", "run", "--allow-net", "--allow-env", "--allow-run", "--allow-read", "migrator/main.ts" ]
